server:
  port: 9000

spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:" # Needed to stop an error.

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true # Route based on information inside eurakaserver Service Registry.
              lowerCaseServiceId: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8000/realms/master/protocol/openid-connect/certs"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
