services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - staj-network


  kafka:
    image: apache/kafka:4.3.1
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: [ "CMD-SHELL", "nc -z kafka 9092 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - staj-network


  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8443:443" # Map host's HTTPS port 8443 to Nginx's 443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../cert.pem:/etc/nginx/certs/cert.pem:ro
      - ../key.pem:/etc/nginx/certs/key.pem:ro
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - staj-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: keycloak
    ports:
      - "8000:8080" # KeyCloak listens on port 8080 by default, map it to host port 8000 to avoid crashing (product-service uses 8080)
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
      KC_HOSTNAME_STRICT_HTTPS: "false" # Disable strict HTTPS validation
      KC_HTTP_ENABLED: "true"           # Ensure HTTP is enabled
      KC_PROXY_HEADERS: "xforwarded"
      KC_HEALTH_ENABLED: "true"         # Enable health endpoint for healthcheck

      # Force Keycloak to identify the issuer as the external https endpoint at port 8443 (not itself at 8080).
      KC_HOSTNAME_URL: "https://localhost:8443"
    command: "start-dev"
    networks:
      - staj-network
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3; grep 'HTTP/1.1 200' <&3"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  productDB:
    image: mysql:latest
    container_name: productDB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productDB
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - staj-network

  stockDB:
    image: mysql:latest
    container_name: stockDB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockDB
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - staj-network

  gatewayserver:
    image: gatewayserver:latest
    container_name: gatewayserver
    ports:
      - "9000:9000"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
      KEYCLOAK_CLIENT_SECRET: "DgPqEDvQEI9SsbGeXDBWZamqqTU8tSp1"
    networks:
      - staj-network
    depends_on:
      eurekaserver:
        condition: service_healthy
      product-service:
        condition: service_healthy
      stock-service:
        condition: service_healthy

  eurekaserver:
    image: eurekaserver:latest
    container_name: eurekaserver
    ports:
      - "8070:8070"
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - staj-network

  product-service:
    image: product:latest
    container_name: product-service
    ports:
      - "8085:8085"
    depends_on:
      productDB:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://productDB:3306/productDB
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SERVER_PORT: 8085
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:29092
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - staj-network

  stock-service:
    image: stock:latest
    container_name: stock-service
    ports:
      - "8090:8090"
      - "8888:8888" # For the temporary Google auth server for gmail.

    depends_on:
      stockDB:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://stockDB:3306/stockDB
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:29092
      MAIL_ADDR: "murat.keceli@agito.com.tr"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - staj-network

networks:
  staj-network:
    driver: bridge

