version: '3.8'

services:
  productDB:
    image: mysql:latest
    container_name: productDB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productDB
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - staj-network

  stockDB:
    image: mysql:latest
    container_name: stockDB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockDB
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - staj-network

  eurekaserver:
    image: eurekaserver:latest
    container_name: eurekaserver
    ports:
      - "8070:8070"
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - staj-network

  product-service:
    image: product:latest
    container_name: product-service
    ports:
      - "8080:8080"
    depends_on:
      productDB:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://productDB:3306/productDB
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - staj-network

  stock-service:
    image: stock:latest
    container_name: stock-service
    ports:
      - "8090:8090"
    depends_on:
      stockDB:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://stockDB:3306/stockDB
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - staj-network

networks:
  staj-network:
    driver: bridge

