server:
  port: 8090

spring:
  application:
    name: "stock"
  datasource:
    url: jdbc:mysql://stockDB:3306/stockDB
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true  # Displays the sql that is run behind the scenes by jdbc.

  cloud:
    loadbalancer:
      cache:
        enabled: true # Disables the load balancer using the cache (for debugging stuck at no instance error)


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted  # Allows graceful shutdown of microservice.
  info: # Enable information related environment variables.
    env:
      enabled: true
endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true # Whenever MS registers to the Eureka S. Make it register via IP (not hostname default).
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# Info on the Eureka Dashboard
info:
  app:
    name: "stock"
    description: "Ecommerce Application"
    version: "1.0.0"


